// Auto-generated by ESBMC 8.2.0
// Test case 3 of 5
// This file provides concrete implementations of __VERIFIER_nondet_* functions

extern "C" {

void __VERIFIER_assume(int cond) { (void)cond; }

unsigned int __VERIFIER_nondet_uint(void) {
  static int i = 0;
  static const unsigned int v[] = { 4294967295, 2147483648 };
  return v[i++];
}

} // extern "C"
