// Auto-generated harness for: libspdm_consttime_is_mem_equal
// Source: corepdk/modules/spdm/src/app/libspdm/os_stub/memlib/compare_mem.c:9
// Generated by Byte Repair Contractor

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

extern bool libspdm_consttime_is_mem_equal(const void *destination_buffer,
                                           const void *source_buffer,
                                           size_t length);

#define HARNESS_MAXLEN 4

void __byterepair_harness_main(void) {
    uint8_t dst[HARNESS_MAXLEN];
    uint8_t src[HARNESS_MAXLEN];
    for (size_t i = 0; i < HARNESS_MAXLEN; i++) {
        dst[i] = nondet_uchar();
        src[i] = nondet_uchar();
    }
    size_t length = nondet_uint();
    __ESBMC_assume(length <= HARNESS_MAXLEN);

    bool result = libspdm_consttime_is_mem_equal(dst, src, length);

    __ESBMC_assert(length != 0 || result == 1, "length==0 implies returns true");
}
