// Auto-generated by ESBMC 8.2.0
// Test case 1 of 1
// This file provides concrete implementations of __VERIFIER_nondet_* functions

extern "C" {

void __VERIFIER_assume(int cond) { (void)cond; }

void* __VERIFIER_nondet_pointer(void) {
  static int i = 0;
  static void* v[] = { 0, 0, 0 };
  return v[i++];
}

unsigned int __VERIFIER_nondet_uint(void) {
  static int i = 0;
  static const unsigned int v[] = { 8 };
  return v[i++];
}

} // extern "C"
