/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Peripherals v15.0
processor: MCXN547
package_id: MCXN547VDF
mcu_data: ksdk2_0
processor_version: 25.09.10
functionalGroups:
- name: BOARD_InitPeripherals
  UUID: 78304674-57e7-4c05-895d-e21c08633a8a
  called_from_default_init: true
  selectedCore: cm33_core0
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'system'
- type_id: 'system_54b53072540eeeb8f8e9343e71f28176'
- global_system_definitions:
  - user_definitions: ''
  - user_includes: ''
  - global_init: ''
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'uart_cmsis_common'
- type_id: 'uart_cmsis_common_9cb8e302497aa696fdbb5a4fd622c2a8'
- global_USART_CMSIS_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/

/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
component:
- type: 'gpio_adapter_common'
- type_id: 'gpio_adapter_common_57579b9ac814fe26bf95df0a384c36b6'
- global_gpio_adapter_common:
  - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "peripherals.h"

/***********************************************************************************************************************
 * BOARD_InitPeripherals functional group
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * DMA0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA0'
- type: 'edma4'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'edma4_2.9.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA0'
- config_sets:
  - fsl_edma:
    - dmamux_devices: []
    - common_settings:
      - vars: []
      - enableHaltOnError: 'true'
      - enableDebugMode: 'false'
      - enableRoundRobinArbitration: 'fixedPriority'
      - enableGlobalChannelLink: 'true'
      - enableMasterIdReplication: 'false'
    - dma_table: []
    - edma_channels: []
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
edma_config_t DMA0_config = {
  .enableMasterIdReplication = false,
  .enableGlobalChannelLink = true,
  .enableHaltOnError = true,
  .enableDebugMode = false,
  .enableRoundRobinArbitration = false
};

/* Empty initialization function (commented out)
static void DMA0_init(void) {
} */

/***********************************************************************************************************************
 * DMA1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'DMA1'
- type: 'edma4'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'edma4_2.9.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'DMA1'
- config_sets:
  - fsl_edma:
    - dmamux_devices: []
    - common_settings:
      - vars: []
      - enableHaltOnError: 'true'
      - enableDebugMode: 'false'
      - enableRoundRobinArbitration: 'fixedPriority'
      - enableGlobalChannelLink: 'true'
      - enableMasterIdReplication: 'false'
    - dma_table: []
    - edma_channels: []
    - quick_selection: 'default'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
edma_config_t DMA1_config = {
  .enableMasterIdReplication = false,
  .enableGlobalChannelLink = true,
  .enableHaltOnError = true,
  .enableDebugMode = false,
  .enableRoundRobinArbitration = false
};

/* Empty initialization function (commented out)
static void DMA1_init(void) {
} */

/***********************************************************************************************************************
 * NVIC initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'NVIC'
- type: 'nvic'
- mode: 'general'
- custom_name_enabled: 'false'
- type_id: 'nvic'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'NVIC'
- config_sets:
  - nvic:
    - interrupt_table:
      - 0: []
    - interrupts: []
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */

/* Empty initialization function (commented out)
static void NVIC_init(void) {
} */

/***********************************************************************************************************************
 * LP_FLEXCOMM3 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM3'
- type: 'lpflexcomm_lpi2c'
- mode: 'interrupt'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpi2c_2.1.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM3'
- config_sets:
  - generalCfg:
    - lpi2c_mode: 'masterSlave'
    - clock_configuration:
      - clockSource: 'LPFLEXCOMMFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master_config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '400000'
      - realBaudRateCount: []
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - enable_dma_master: 'false'
      - lpi2c_dma_master_struct_t:
        - DMATxEnable: 'true'
        - DMARxEnable: 'true'
    - slave_config:
      - enableSlave: 'true'
      - iAddress0: '0x52'
      - iAddress1: '0'
      - addressMatchMode: 'kLPI2C_MatchAddress0'
      - filterEnable: 'true'
      - filterDozeEnable: 'true'
      - enableGeneralCall: 'false'
      - sclStall:
        - enableAck: 'false'
        - enableTx: 'true'
        - enableRx: 'true'
        - enableAddress: 'false'
      - ignoreAck: 'false'
      - enableReceivedAddressRead: 'false'
      - slaveMaxMinValue: []
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - dataValidDelay_ns: '0'
      - clockHoldTime_ns: '0'
      - enable_dma_slave: 'false'
      - lpi2c_dma_slave_struct_t:
        - enableAddressValid: 'false'
        - DMATxEnable: 'true'
        - DMARxEnable: 'true'
  - interrupt:
    - master_flags: 'kLPI2C_MasterTxReadyFlag kLPI2C_MasterRxReadyFlag kLPI2C_MasterStopDetectFlag kLPI2C_MasterNackDetectFlag kLPI2C_MasterArbitrationLostFlag
      kLPI2C_MasterFifoErrFlag kLPI2C_MasterPinLowTimeoutFlag'
    - slave_flags: 'kLPI2C_SlaveTxReadyFlag kLPI2C_SlaveRxReadyFlag kLPI2C_SlaveAddressValidFlag kLPI2C_SlaveTransmitAckFlag kLPI2C_SlaveRepeatedStartDetectFlag
      kLPI2C_SlaveStopDetectFlag kLPI2C_SlaveBitErrFlag'
    - enable_irq: 'false'
    - interrupt:
      - IRQn: 'LP_FLEXCOMM3_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LP_FLEXCOMM3_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 400000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
const lpi2c_slave_config_t LP_FLEXCOMM3_slaveConfig = {
  .enableSlave = true,
  .address0 = LP_FLEXCOMM3_SLAVE_ADDRESS0,
  .address1 = LP_FLEXCOMM3_SLAVE_ADDRESS1,
  .addressMatchMode = kLPI2C_MatchAddress0,
  .filterEnable = true,
  .filterDozeEnable = true,
  .enableGeneralCall = false,
  .sclStall = {
    .enableAck = false,
    .enableTx = true,
    .enableRx = true,
    .enableAddress = false
  },
  .ignoreAck = false,
  .enableReceivedAddressRead = false,
  .sdaGlitchFilterWidth_ns = 0UL,
  .sclGlitchFilterWidth_ns = 0UL,
  .dataValidDelay_ns = 0UL,
  .clockHoldTime_ns = 0UL
};

static void LP_FLEXCOMM3_init(void) {
  /* LP_FLEXCOMM3 LPI2C leader initialization */
  LPI2C_MasterInit(LP_FLEXCOMM3_PERIPHERAL, &LP_FLEXCOMM3_masterConfig, LP_FLEXCOMM3_CLOCK_SOURCE);
  /* LP_FLEXCOMM3 LPI2C follower initialization */
  LPI2C_SlaveInit(LP_FLEXCOMM3_PERIPHERAL, &LP_FLEXCOMM3_slaveConfig, LP_FLEXCOMM3_CLOCK_SOURCE);
  /* LP_FLEXCOMM3 LPI2C leader interrupt sources */
  LPI2C_MasterEnableInterrupts(LP_FLEXCOMM3_PERIPHERAL, (uint32_t)(kLPI2C_MasterTxReadyFlag | kLPI2C_MasterRxReadyFlag | kLPI2C_MasterStopDetectFlag | kLPI2C_MasterNackDetectFlag | kLPI2C_MasterArbitrationLostFlag | kLPI2C_MasterFifoErrFlag | kLPI2C_MasterPinLowTimeoutFlag));
  /* LP_FLEXCOMM3 LPI2C follower interrupt sources */
  LPI2C_SlaveEnableInterrupts(LP_FLEXCOMM3_PERIPHERAL, (uint32_t)(kLPI2C_SlaveTxReadyFlag | kLPI2C_SlaveRxReadyFlag | kLPI2C_SlaveAddressValidFlag | kLPI2C_SlaveTransmitAckFlag | kLPI2C_SlaveRepeatedStartDetectFlag | kLPI2C_SlaveStopDetectFlag | kLPI2C_SlaveBitErrFlag));
}

/***********************************************************************************************************************
 * LP_FLEXCOMM1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM1'
- type: 'lpflexcomm_lpi2c'
- mode: 'interrupt'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpi2c_2.1.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM1'
- config_sets:
  - generalCfg:
    - lpi2c_mode: 'masterSlave'
    - clock_configuration:
      - clockSource: 'LPFLEXCOMMFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master_config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '100000'
      - realBaudRateCount: []
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - enable_dma_master: 'false'
      - lpi2c_dma_master_struct_t:
        - DMATxEnable: 'true'
        - DMARxEnable: 'true'
    - slave_config:
      - enableSlave: 'true'
      - iAddress0: '0x62'
      - iAddress1: '0'
      - addressMatchMode: 'kLPI2C_MatchAddress0'
      - filterEnable: 'true'
      - filterDozeEnable: 'true'
      - enableGeneralCall: 'false'
      - sclStall:
        - enableAck: 'false'
        - enableTx: 'true'
        - enableRx: 'true'
        - enableAddress: 'false'
      - ignoreAck: 'false'
      - enableReceivedAddressRead: 'false'
      - slaveMaxMinValue: []
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - dataValidDelay_ns: '0'
      - clockHoldTime_ns: '0'
      - enable_dma_slave: 'false'
      - lpi2c_dma_slave_struct_t:
        - enableAddressValid: 'false'
        - DMATxEnable: 'true'
        - DMARxEnable: 'true'
  - interrupt:
    - master_flags: 'kLPI2C_MasterTxReadyFlag kLPI2C_MasterRxReadyFlag kLPI2C_MasterStopDetectFlag kLPI2C_MasterNackDetectFlag kLPI2C_MasterArbitrationLostFlag
      kLPI2C_MasterFifoErrFlag kLPI2C_MasterPinLowTimeoutFlag'
    - slave_flags: 'kLPI2C_SlaveTxReadyFlag kLPI2C_SlaveRxReadyFlag kLPI2C_SlaveAddressValidFlag kLPI2C_SlaveTransmitAckFlag kLPI2C_SlaveRepeatedStartDetectFlag
      kLPI2C_SlaveStopDetectFlag kLPI2C_SlaveBitErrFlag'
    - enable_irq: 'false'
    - interrupt:
      - IRQn: 'LP_FLEXCOMM1_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LP_FLEXCOMM1_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 100000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
const lpi2c_slave_config_t LP_FLEXCOMM1_slaveConfig = {
  .enableSlave = true,
  .address0 = LP_FLEXCOMM1_SLAVE_ADDRESS0,
  .address1 = LP_FLEXCOMM1_SLAVE_ADDRESS1,
  .addressMatchMode = kLPI2C_MatchAddress0,
  .filterEnable = true,
  .filterDozeEnable = true,
  .enableGeneralCall = false,
  .sclStall = {
    .enableAck = false,
    .enableTx = true,
    .enableRx = true,
    .enableAddress = false
  },
  .ignoreAck = false,
  .enableReceivedAddressRead = false,
  .sdaGlitchFilterWidth_ns = 0UL,
  .sclGlitchFilterWidth_ns = 0UL,
  .dataValidDelay_ns = 0UL,
  .clockHoldTime_ns = 0UL
};

static void LP_FLEXCOMM1_init(void) {
  /* LP_FLEXCOMM1 LPI2C leader initialization */
  LPI2C_MasterInit(LP_FLEXCOMM1_PERIPHERAL, &LP_FLEXCOMM1_masterConfig, LP_FLEXCOMM1_CLOCK_SOURCE);
  /* LP_FLEXCOMM1 LPI2C follower initialization */
  LPI2C_SlaveInit(LP_FLEXCOMM1_PERIPHERAL, &LP_FLEXCOMM1_slaveConfig, LP_FLEXCOMM1_CLOCK_SOURCE);
  /* LP_FLEXCOMM1 LPI2C leader interrupt sources */
  LPI2C_MasterEnableInterrupts(LP_FLEXCOMM1_PERIPHERAL, (uint32_t)(kLPI2C_MasterTxReadyFlag | kLPI2C_MasterRxReadyFlag | kLPI2C_MasterStopDetectFlag | kLPI2C_MasterNackDetectFlag | kLPI2C_MasterArbitrationLostFlag | kLPI2C_MasterFifoErrFlag | kLPI2C_MasterPinLowTimeoutFlag));
  /* LP_FLEXCOMM1 LPI2C follower interrupt sources */
  LPI2C_SlaveEnableInterrupts(LP_FLEXCOMM1_PERIPHERAL, (uint32_t)(kLPI2C_SlaveTxReadyFlag | kLPI2C_SlaveRxReadyFlag | kLPI2C_SlaveAddressValidFlag | kLPI2C_SlaveTransmitAckFlag | kLPI2C_SlaveRepeatedStartDetectFlag | kLPI2C_SlaveStopDetectFlag | kLPI2C_SlaveBitErrFlag));
}

/***********************************************************************************************************************
 * LP_FLEXCOMM0 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM0'
- type: 'lpflexcomm_lpi2c'
- mode: 'interrupt'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpi2c_2.1.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM0'
- config_sets:
  - generalCfg:
    - lpi2c_mode: 'masterSlave'
    - clock_configuration:
      - clockSource: 'LPFLEXCOMMFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master_config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '100000'
      - realBaudRateCount: []
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - enable_dma_master: 'false'
      - lpi2c_dma_master_struct_t:
        - DMATxEnable: 'true'
        - DMARxEnable: 'true'
    - slave_config:
      - enableSlave: 'true'
      - iAddress0: '0x52'
      - iAddress1: '0'
      - addressMatchMode: 'kLPI2C_MatchAddress0'
      - filterEnable: 'true'
      - filterDozeEnable: 'true'
      - enableGeneralCall: 'false'
      - sclStall:
        - enableAck: 'false'
        - enableTx: 'true'
        - enableRx: 'true'
        - enableAddress: 'false'
      - ignoreAck: 'false'
      - enableReceivedAddressRead: 'false'
      - slaveMaxMinValue: []
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - dataValidDelay_ns: '0'
      - clockHoldTime_ns: '0'
      - enable_dma_slave: 'false'
      - lpi2c_dma_slave_struct_t:
        - enableAddressValid: 'false'
        - DMATxEnable: 'true'
        - DMARxEnable: 'true'
  - interrupt:
    - master_flags: 'kLPI2C_MasterTxReadyFlag kLPI2C_MasterRxReadyFlag kLPI2C_MasterStopDetectFlag kLPI2C_MasterNackDetectFlag kLPI2C_MasterArbitrationLostFlag
      kLPI2C_MasterFifoErrFlag kLPI2C_MasterPinLowTimeoutFlag'
    - slave_flags: 'kLPI2C_SlaveTxReadyFlag kLPI2C_SlaveRxReadyFlag kLPI2C_SlaveAddressValidFlag kLPI2C_SlaveTransmitAckFlag kLPI2C_SlaveRepeatedStartDetectFlag
      kLPI2C_SlaveStopDetectFlag kLPI2C_SlaveBitErrFlag'
    - enable_irq: 'false'
    - interrupt:
      - IRQn: 'LP_FLEXCOMM0_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LP_FLEXCOMM0_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 100000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};
const lpi2c_slave_config_t LP_FLEXCOMM0_slaveConfig = {
  .enableSlave = true,
  .address0 = LP_FLEXCOMM0_SLAVE_ADDRESS0,
  .address1 = LP_FLEXCOMM0_SLAVE_ADDRESS1,
  .addressMatchMode = kLPI2C_MatchAddress0,
  .filterEnable = true,
  .filterDozeEnable = true,
  .enableGeneralCall = false,
  .sclStall = {
    .enableAck = false,
    .enableTx = true,
    .enableRx = true,
    .enableAddress = false
  },
  .ignoreAck = false,
  .enableReceivedAddressRead = false,
  .sdaGlitchFilterWidth_ns = 0UL,
  .sclGlitchFilterWidth_ns = 0UL,
  .dataValidDelay_ns = 0UL,
  .clockHoldTime_ns = 0UL
};

static void LP_FLEXCOMM0_init(void) {
  /* LP_FLEXCOMM0 LPI2C leader initialization */
  LPI2C_MasterInit(LP_FLEXCOMM0_PERIPHERAL, &LP_FLEXCOMM0_masterConfig, LP_FLEXCOMM0_CLOCK_SOURCE);
  /* LP_FLEXCOMM0 LPI2C follower initialization */
  LPI2C_SlaveInit(LP_FLEXCOMM0_PERIPHERAL, &LP_FLEXCOMM0_slaveConfig, LP_FLEXCOMM0_CLOCK_SOURCE);
  /* LP_FLEXCOMM0 LPI2C leader interrupt sources */
  LPI2C_MasterEnableInterrupts(LP_FLEXCOMM0_PERIPHERAL, (uint32_t)(kLPI2C_MasterTxReadyFlag | kLPI2C_MasterRxReadyFlag | kLPI2C_MasterStopDetectFlag | kLPI2C_MasterNackDetectFlag | kLPI2C_MasterArbitrationLostFlag | kLPI2C_MasterFifoErrFlag | kLPI2C_MasterPinLowTimeoutFlag));
  /* LP_FLEXCOMM0 LPI2C follower interrupt sources */
  LPI2C_SlaveEnableInterrupts(LP_FLEXCOMM0_PERIPHERAL, (uint32_t)(kLPI2C_SlaveTxReadyFlag | kLPI2C_SlaveRxReadyFlag | kLPI2C_SlaveAddressValidFlag | kLPI2C_SlaveTransmitAckFlag | kLPI2C_SlaveRepeatedStartDetectFlag | kLPI2C_SlaveStopDetectFlag | kLPI2C_SlaveBitErrFlag));
}

/***********************************************************************************************************************
 * LP_FLEXCOMM7 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM7'
- type: 'lpflexcomm_lpspi'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpspi_2.2.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM7'
- config_sets:
  - main:
    - mode: 'kLPSPI_Master'
    - clockSource: 'clk_src0'
    - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master:
      - baudRateBps: '24000000'
      - bitsPerFrame: '8'
      - cpol: 'kLPSPI_ClockPolarityActiveHigh'
      - cpha: 'kLPSPI_ClockPhaseFirstEdge'
      - direction: 'kLPSPI_MsbFirst'
      - pcsToSckDelayInNanoSec: '1000'
      - lastSckToPcsDelayInNanoSec: '1000'
      - betweenTransferDelayInNanoSec: '1000'
      - whichPcs: 'kLPSPI_Pcs0'
      - pcsActiveHighOrLow: 'kLPSPI_PcsActiveLow'
      - pinCfg: 'kLPSPI_SdiInSdoOut'
      - pcsFunc: 'kLPSPI_PcsAsCs'
      - dataOutConfig: 'kLpspiDataOutRetained'
      - enableInputDelay: 'false'
    - set_FifoWaterMarks: 'false'
    - fifoWaterMarks:
      - txWatermark: '0'
      - rxWatermark: '0'
    - allPcsPolarityEnable: 'false'
    - allPcsPolarity:
      - kLPSPI_Pcs1Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs2Active: 'kLPSPI_PcsActiveLow'
      - kLPSPI_Pcs3Active: 'kLPSPI_PcsActiveLow'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpspi_master_config_t LP_FLEXCOMM7_config = {
  .baudRate = 24000000UL,
  .bitsPerFrame = 8UL,
  .cpol = kLPSPI_ClockPolarityActiveHigh,
  .cpha = kLPSPI_ClockPhaseFirstEdge,
  .direction = kLPSPI_MsbFirst,
  .pcsToSckDelayInNanoSec = 1000UL,
  .lastSckToPcsDelayInNanoSec = 1000UL,
  .betweenTransferDelayInNanoSec = 1000UL,
  .whichPcs = kLPSPI_Pcs0,
  .pcsActiveHighOrLow = kLPSPI_PcsActiveLow,
  .pinCfg = kLPSPI_SdiInSdoOut,
  .pcsFunc = kLPSPI_PcsAsCs,
  .dataOutConfig = kLpspiDataOutRetained,
  .enableInputDelay = false
};

static void LP_FLEXCOMM7_init(void) {
  LPSPI_MasterInit(LP_FLEXCOMM7_PERIPHERAL, &LP_FLEXCOMM7_config, LP_FLEXCOMM7_CLOCK_FREQ);
}

/***********************************************************************************************************************
 * LP_FLEXCOMM6 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM6'
- type: 'lpflexcomm_lpi2c'
- mode: 'interrupt'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpi2c_2.1.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM6'
- config_sets:
  - generalCfg:
    - lpi2c_mode: 'master'
    - clock_configuration:
      - clockSource: 'LPFLEXCOMMFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master_config:
      - enableMaster: 'true'
      - enableDoze: 'true'
      - debugEnable: 'false'
      - ignoreAck: 'false'
      - pinConfig: 'kLPI2C_2PinOpenDrain'
      - baudRate_Hz: '400000'
      - realBaudRateCount: []
      - busIdleTimeout_ns: '0'
      - pinLowTimeout_ns: '0'
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - hostRequest:
        - enable: 'false'
        - source: 'kLPI2C_HostRequestExternalPin'
        - polarity: 'kLPI2C_HostRequestPinActiveHigh'
      - enable_dma_master: 'false'
      - lpi2c_dma_master_struct_t:
        - DMATxEnable: 'true'
        - DMARxEnable: 'true'
  - interrupt:
    - master_flags: 'kLPI2C_MasterTxReadyFlag kLPI2C_MasterRxReadyFlag kLPI2C_MasterStopDetectFlag kLPI2C_MasterNackDetectFlag kLPI2C_MasterArbitrationLostFlag
      kLPI2C_MasterFifoErrFlag kLPI2C_MasterPinLowTimeoutFlag'
    - enable_irq: 'true'
    - interrupt:
      - IRQn: 'LP_FLEXCOMM6_IRQn'
      - enable_interrrupt: 'enabled'
      - enable_priority: 'false'
      - priority: '0'
      - enable_custom_name: 'false'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_master_config_t LP_FLEXCOMM6_masterConfig = {
  .enableMaster = true,
  .enableDoze = true,
  .debugEnable = false,
  .ignoreAck = false,
  .pinConfig = kLPI2C_2PinOpenDrain,
  .baudRate_Hz = 400000UL,
  .busIdleTimeout_ns = 0UL,
  .pinLowTimeout_ns = 0UL,
  .sdaGlitchFilterWidth_ns = 0U,
  .sclGlitchFilterWidth_ns = 0U,
  .hostRequest = {
    .enable = false,
    .source = kLPI2C_HostRequestExternalPin,
    .polarity = kLPI2C_HostRequestPinActiveHigh
  }
};

static void LP_FLEXCOMM6_init(void) {
  /* LP_FLEXCOMM6 LPI2C leader initialization */
  LPI2C_MasterInit(LP_FLEXCOMM6_PERIPHERAL, &LP_FLEXCOMM6_masterConfig, LP_FLEXCOMM6_CLOCK_SOURCE);
  /* LP_FLEXCOMM6 LPI2C leader interrupt sources */
  LPI2C_MasterEnableInterrupts(LP_FLEXCOMM6_PERIPHERAL, (uint32_t)(kLPI2C_MasterTxReadyFlag | kLPI2C_MasterRxReadyFlag | kLPI2C_MasterStopDetectFlag | kLPI2C_MasterNackDetectFlag | kLPI2C_MasterArbitrationLostFlag | kLPI2C_MasterFifoErrFlag | kLPI2C_MasterPinLowTimeoutFlag));
  /* Enable interrupt LP_FLEXCOMM6_IRQN request in the NVIC */
  EnableIRQ(LP_FLEXCOMM6_IRQN);
}

/***********************************************************************************************************************
 * LP_FLEXCOMM4 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM4'
- type: 'lpflexcomm_lpuart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpuart_2.3.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM4'
- config_sets:
  - fsl_lpuart:
    - lpuartConfig:
      - timingConfig:
        - clockSource: 'LPFLEXCOMMFunctionClock'
        - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
        - baudRateBpsStr: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - rtsDelayValue: '1'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableSingleWire: 'false'
      - enableTx: 'true'
      - enableRx: 'true'
      - timeoutConfig:
        - rxExtendedTimeoutValue: '0'
        - txExtendedTimeoutValue: '0'
        - rxCounter0:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - rxCounter1:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - txCounter0:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - txCounter1:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LP_FLEXCOMM4_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableSingleWire = false,
  .rtsDelay = 0,
  .enableTx = true,
  .enableRx = true,
  .timeoutConfig = {
    .rxExtendedTimeoutValue = 0U,
    .txExtendedTimeoutValue = 0U,
    .rxCounter0 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .rxCounter1 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .txCounter0 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .txCounter1 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    }
  }
};

static void LP_FLEXCOMM4_init(void) {
  LPUART_Init(LP_FLEXCOMM4_PERIPHERAL, &LP_FLEXCOMM4_config, LP_FLEXCOMM4_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * LP_FLEXCOMM2 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM2'
- type: 'lpflexcomm_lpi2c'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpi2c_2.1.1'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM2'
- config_sets:
  - generalCfg:
    - lpi2c_mode: 'slave'
    - clock_configuration:
      - clockSource: 'LPFLEXCOMMFunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - slave_config:
      - enableSlave: 'false'
      - iAddress0: '0x10'
      - iAddress1: '0x0C'
      - addressMatchMode: 'kLPI2C_MatchAddress0OrAddress1'
      - filterEnable: 'true'
      - filterDozeEnable: 'true'
      - enableGeneralCall: 'false'
      - sclStall:
        - enableAck: 'true'
        - enableTx: 'true'
        - enableRx: 'true'
        - enableAddress: 'true'
      - ignoreAck: 'false'
      - enableReceivedAddressRead: 'false'
      - slaveMaxMinValue: []
      - sdaGlitchFilterWidth_ns: '0'
      - sclGlitchFilterWidth_ns: '0'
      - dataValidDelay_ns: '0'
      - clockHoldTime_ns: '0'
      - enable_dma_slave: 'false'
      - lpi2c_dma_slave_struct_t:
        - enableAddressValid: 'false'
        - DMATxEnable: 'true'
        - DMARxEnable: 'true'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpi2c_slave_config_t LP_FLEXCOMM2_slaveConfig = {
  .enableSlave = false,
  .address0 = LP_FLEXCOMM2_SLAVE_ADDRESS0,
  .address1 = LP_FLEXCOMM2_SLAVE_ADDRESS1,
  .addressMatchMode = kLPI2C_MatchAddress0OrAddress1,
  .filterEnable = true,
  .filterDozeEnable = true,
  .enableGeneralCall = false,
  .sclStall = {
    .enableAck = true,
    .enableTx = true,
    .enableRx = true,
    .enableAddress = true
  },
  .ignoreAck = false,
  .enableReceivedAddressRead = false,
  .sdaGlitchFilterWidth_ns = 0UL,
  .sclGlitchFilterWidth_ns = 0UL,
  .dataValidDelay_ns = 0UL,
  .clockHoldTime_ns = 0UL
};

static void LP_FLEXCOMM2_init(void) {
  /* LP_FLEXCOMM2 LPI2C follower initialization */
  LPI2C_SlaveInit(LP_FLEXCOMM2_PERIPHERAL, &LP_FLEXCOMM2_slaveConfig, LP_FLEXCOMM2_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * I3C1 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'I3C1'
- type: 'i3c'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'i3c_2.12.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'I3C1'
- config_sets:
  - fsl_i3c:
    - i3c_mode: 'master'
    - clock_config_master:
      - clockSource: 'FunctionClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - clock_config_slave:
      - clockSource: 'SlowClock'
      - clockSourceFreq: 'ClocksTool_DefaultInit'
    - master_config:
      - enableMaster: 'kI3C_MasterOn'
      - disableTimeout: 'false'
      - hKeep: 'kI3C_MasterHighKeeperNone'
      - enableOpenDrainStop: 'true'
      - enableOpenDrainHigh: 'true'
      - baudRate_Hz:
        - i3cPushPullBaud: '12500000'
        - i3cOpenDrainBaud: '2500000'
        - i2cBaud: '400000'
    - quick_selection: 'QS_I3C_1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const i3c_master_config_t I3C1_master_config = {
  .enableMaster = kI3C_MasterOn,
  .disableTimeout = false,
  .hKeep = kI3C_MasterHighKeeperNone,
  .enableOpenDrainStop = true,
  .enableOpenDrainHigh = true,
  .baudRate_Hz = {
    .i3cPushPullBaud = 12500000UL,
    .i3cOpenDrainBaud = 2500000UL,
    .i2cBaud = 400000UL
  },
  .slowClock_Hz = I3C1_SLOW_CLOCK_SOURCE,
};

static void I3C1_init(void) {
  /* Initialization function */
  I3C_MasterInit(I3C1_PERIPHERAL, &I3C1_master_config, I3C1_CLOCK_SOURCE_MASTER);
}

/***********************************************************************************************************************
 * LP_FLEXCOMM9 initialization code
 **********************************************************************************************************************/
/* clang-format off */
/* TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
instance:
- name: 'LP_FLEXCOMM9'
- type: 'lpflexcomm_lpuart'
- mode: 'polling'
- custom_name_enabled: 'false'
- type_id: 'lpflexcomm_lpuart_2.3.0'
- functional_group: 'BOARD_InitPeripherals'
- peripheral: 'LP_FLEXCOMM9'
- config_sets:
  - fsl_lpuart:
    - lpuartConfig:
      - timingConfig:
        - clockSource: 'LPFLEXCOMMFunctionClock'
        - lpuartSrcClkFreq: 'ClocksTool_DefaultInit'
        - baudRateBpsStr: '115200'
      - parityMode: 'kLPUART_ParityDisabled'
      - dataBitsCount: 'kLPUART_EightDataBits'
      - isMsb: 'false'
      - stopBitCount: 'kLPUART_OneStopBit'
      - enableMatchAddress1: 'false'
      - matchAddress1: '0'
      - enableMatchAddress2: 'false'
      - matchAddress2: '0'
      - txFifoWatermark: '0'
      - rxFifoWatermark: '1'
      - enableRxRTS: 'false'
      - rtsDelayValue: '1'
      - enableTxCTS: 'false'
      - txCtsSource: 'kLPUART_CtsSourcePin'
      - txCtsConfig: 'kLPUART_CtsSampleAtStart'
      - rxIdleType: 'kLPUART_IdleTypeStartBit'
      - rxIdleConfig: 'kLPUART_IdleCharacter1'
      - enableSingleWire: 'false'
      - enableTx: 'true'
      - enableRx: 'true'
      - timeoutConfig:
        - rxExtendedTimeoutValue: '0'
        - txExtendedTimeoutValue: '0'
        - rxCounter0:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - rxCounter1:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - txCounter0:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
        - txCounter1:
          - enableCounter: 'false'
          - timeoutCondition: 'kLPUART_TimeoutAfterCharacters'
          - timeoutValue: '0'
    - quick_selection: 'QuickSelection1'
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS **********/
/* clang-format on */
const lpuart_config_t LP_FLEXCOMM9_config = {
  .baudRate_Bps = 115200UL,
  .parityMode = kLPUART_ParityDisabled,
  .dataBitsCount = kLPUART_EightDataBits,
  .isMsb = false,
  .stopBitCount = kLPUART_OneStopBit,
  .txFifoWatermark = 0U,
  .rxFifoWatermark = 1U,
  .enableRxRTS = false,
  .enableTxCTS = false,
  .txCtsSource = kLPUART_CtsSourcePin,
  .txCtsConfig = kLPUART_CtsSampleAtStart,
  .rxIdleType = kLPUART_IdleTypeStartBit,
  .rxIdleConfig = kLPUART_IdleCharacter1,
  .enableSingleWire = false,
  .rtsDelay = 0,
  .enableTx = true,
  .enableRx = true,
  .timeoutConfig = {
    .rxExtendedTimeoutValue = 0U,
    .txExtendedTimeoutValue = 0U,
    .rxCounter0 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .rxCounter1 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .txCounter0 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    },
    .txCounter1 = {
      .enableCounter = false,
      .timeoutCondition = kLPUART_TimeoutAfterCharacters,
      .timeoutValue = 0U
    }
  }
};

static void LP_FLEXCOMM9_init(void) {
  LPUART_Init(LP_FLEXCOMM9_PERIPHERAL, &LP_FLEXCOMM9_config, LP_FLEXCOMM9_CLOCK_SOURCE);
}

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void)
{
  /* Global initialization */
  (void)memset(DMA0_config.channelConfig, 0, FSL_FEATURE_EDMA_INSTANCE_CHANNELn(DMA0_DMA_BASEADDR) * sizeof(edma_channel_config_t *));
  EDMA_Init(DMA0_DMA_BASEADDR, &DMA0_config);
  (void)memset(DMA1_config.channelConfig, 0, FSL_FEATURE_EDMA_INSTANCE_CHANNELn(DMA1_DMA_BASEADDR) * sizeof(edma_channel_config_t *));
  EDMA_Init(DMA1_DMA_BASEADDR, &DMA1_config);

  /* Initialize components */
  LP_FLEXCOMM3_init();
  LP_FLEXCOMM1_init();
  LP_FLEXCOMM0_init();
  LP_FLEXCOMM7_init();
  LP_FLEXCOMM6_init();
  LP_FLEXCOMM4_init();
  LP_FLEXCOMM2_init();
  I3C1_init();
  LP_FLEXCOMM9_init();
}

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void)
{
  BOARD_InitPeripherals();
}
